### ISSUE TITLE
Create a index.html file

### ISSUE THREAD

**Issue by cosminmemetea** [cosminmemetea/AzureBoards#1]
The file shall have no content inside.
After the file is created just commit it as it is.

**Comment by cosminmemetea** [comment]
Create a pull request for this commit.

**Comment by BiancaTicarat** [comment]
1) Where should be index.html ?
2)"The file shall have no content inside" it's not clear for me.
3) How to create a pull request for this commit.

**Comment by cosminmemetea** [comment]
@BiancaTicarat Glad you asked :) .
1) the index.html file shall be place in a folder named "app" 
2) the "app" folder shall be in the same folder as README.md file. As a hint: in VSCode right click on the AzureBoards project then choose to create a new folder.
3) index.html file it's an empty file with no text within whose name is index.html
4)The pull request part is no longer required for this task.

**Comment by cosminmemetea** [comment]
Fix cosminmemetea/AzureBoards#1

**Comment by cosminmemetea** [comment]
The third requirement is not satisfied. The index.html file shall be empty.
